version: "0.2"

env:
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
      - rustup default stable
      - rustup update
      - rustup update nightly
      - rustup target add wasm32-unknown-unknown --toolchain nightly
  build:
    commands:
      - cargo test --package pallet-dids --lib tests
      - apt install llvm clang
      - cargo build --release

artifacts:
  files:
    - target/release/trackback-node
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*
