version: "3.2"

services:
  health:
    image: donlokuge/nginx-hello
    container_name: nginx-hello
    ports:
        - "80:80"
  dev:
    container_name: trackback-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/trackback-node
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/trackback-node.cargo
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    volumes:
      - .:/var/www/trackback-node
      - type: bind
        source: ./.local
        target: /root/.local
    logging:
      driver: awslogs
      options:
        awslogs-group: substrate
        awslogs-region: ap-southeast-2
        awslogs-stream: trackbackNode
    command: bash -c "cargo build --release && RUST_LOG=debug RUST_BACKTRACE=1 ./target/release/trackback-node -lruntime=debug --dev"
