name: TrackBack Test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Test and Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          docker build -f ./docker/Dockerfile.test -t trackback-node-test .
          docker run --rm trackback-node-test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: |
          docker build -f ./docker/Dockerfile.prod -t trackback-node .
          docker images

