name: TrackBack Test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Nightly
        run:  |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source ~/.cargo/env
          rustup default stable
          rustup update
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly -y
      - name: Build
        run: |
          cargo update -p parity-db
          cargo build
      - name: Run tests
        run:  cargo test --package pallet-dids --lib tests --verbose;
