name: TrackBack Test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Test and Docker Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          docker build -f ./docker/Dockerfile.test -t trackback-node-test .
          docker run --rm trackback-node-test
      - name: Login to Docker Hub
        env:
          DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_HUB_USER_NAME -p $DOCKER_HUB_PASSWORD
      - name: Build
        run: |
          docker build -f ./docker/Dockerfile.prod -t trackbacklimited/trackbacknode .
          docker images
      - name: Docker Push
        run: |
          docker push $DOCKER_HUB_USER_NAME/trackbacknode

