name: TrackBack Test

on:
  [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clean
        run: cargo update -p parity-db && cargo clean
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run:  cargo test --package pallet-dids --lib tests --verbose;
